const CHARACTERS = [
    // Great Old Ones
    { id: 1, name: 'Ancient Sun God', gender: 'Male', species: ['Human'], pathway: ['Visionary', 'Sun', 'Tyrant', 'White Tower', 'Hanged Man'], sequence: 'Above the Sequence', volume: 2, affiliation: ['❌'], epoch: 'Pre-Epoch' },
    { id: 2, name: 'Original Creator', gender: '❌', species: ['❌'], pathway: ['All Pathways'], sequence: 'Above the Sequence', volume: 1, affiliation: ['❌'], epoch: 'Pre-Epoch' },  
    { id: 3, name: 'Celestial Worthy of Heaven and Earth for Blessings', gender: '❌', species: ['Great Old One'], pathway: ['Fool', 'Error', 'Door'], sequence: 'Above the Sequence', volume: 1, affiliation: ['❌'], epoch: 'Pre-Epoch' },
    { id: 4, name: 'Klein Moretti', gender: 'Male', species: ['Human'], pathway: ['Fool', 'Error', 'Door'], sequence: 'Above the Sequence', volume: 1, affiliation: ['Tarot Club'], epoch: 'Pre-Epoch' },
    { id: 5, name: 'Mother Goddess of Depravity', gender: 'Female', species: ['Outer Deity'], pathway: ['Mother', 'Moon'], sequence: 'Above the Sequence', volume: 2, affiliation: ['❌'], epoch: 'Pre-Epoch' },
    { id: 6, name: 'Mother Tree of Desire', gender: 'Female', species: ['Outer Deity'], pathway: ['Abyss', 'Chained'], sequence: 'Above the Sequence', volume: 3, affiliation: ['❌'], epoch: 'Pre-Epoch' },
    { id: 7, name: 'Primordial God Almighty', gender: '❌', species: ['Great Old One'], pathway: ['Visionary', 'Sun', 'Tyrant', 'White Tower', 'Hanged Man'], sequence: 'Above the Sequence', volume: 6, affiliation: ['❌'], epoch: 'Pre-Epoch' },

    // Gods
    { id: 8, name: 'Adam', gender: 'Male', species: ['Mythical Creature'], pathway: ['Visionary'], sequence: 0, volume: 2, affiliation: ['Twilight Hermit Order'], epoch: 'Third Epoch' },
    { id: 9, name: 'Alista Tudor', gender: 'Male', species: ['Human'], pathway: ['Red Priest'], sequence: 0, volume: 1, affiliation: ['❌'], epoch: 'Fourth Epoch' },
    { id: 10, name: 'Ankewelt', gender: 'Male', species: ['Dragon'], pathway: ['Visionary'], sequence: 0, volume: 2, affiliation: ['❌'], epoch: 'Second Epoch' },
    { id: 11, name: 'Aurmir', gender: 'Male', species: ['Giant'], pathway: 'Twilight Giant', sequence: 0, volume: 1, affiliation: ['❌'], epoch: 'Second Epoch' },
    { id: 12, name: 'Eternal Blazing Sun', gender: 'Male', species: ['Human'], pathway: ['Sun'], sequence: 0, volume: 1, affiliation: ['Church of the Eternal Blazing Sun', 'Rose Redemption'], epoch: 'Third Epoch' },
    { id: 13, name: 'Evernight Goddess', gender: 'Female', species: ['Demonic Wolf'], pathway: ['Darkness'], sequence: 0, volume: 1, affiliation: ['Church of the Evernight Goddess'], epoch: 'Pre-Epoch' },
    { id: 14, name: 'Farbauti', gender: 'Male', species: ['Human'], pathway: ['Abyss'], sequence: 0, volume: 5, affiliation: ['❌'], epoch: 'Second Epoch' },
    { id: 15, name: 'Flegrea', gender: 'Male', species: ['Demonic Wolf'], pathway: 'Darkness', sequence: 0, volume: 1, affiliation: ['❌'], epoch: 'Second Epoch' },
    { id: 16, name: 'God of Combat', gender: 'Male', species: ['Giant'], pathway: ['Twilight Giant'], sequence: 0, volume: 1, affiliation: ['Church of the God of Combat', 'Rose Redemption'], epoch: 'Second Epoch' },
    { id: 17, name: 'God of Knowledge and Wisdom', gender: 'Male', species: ['Dragon'], pathway: ['White Tower'], sequence: 0, volume: 1, affiliation: ['Church of the God of Knowledge and Wisdom', 'Rose Redemption'], epoch: 'Third Epoch' },
    { id: 18, name: 'God of Steam and Machinery', gender: 'Male', species: ['❌'], pathway: ['Paragon'], sequence: 0, volume: 1, affiliation: ['Church of the God of Steam and Machinery'], epoch: 'Third Epoch' },
    { id: 19, name: 'Gregrace', gender: 'Female', species: ['Phoenix'], pathway: ['Death'], sequence: 0, volume: 2, affiliation: ['❌'], epoch: 'Second Epoch' },
    { id: 20, name: 'Kvastir', gender: 'Male', species: ['Mutant'], pathway: ['Chained'], sequence: 0, volume: 2, affiliation: ['❌'], epoch: 'Second Epoch' },
    { id: 21, name: 'Lilith', gender: 'Female', species: ['Sanguine'], pathway: ['Mother'], sequence: 0, volume: 1, affiliation: ['Church of the Earth Mother', 'Sanguines', 'Rose Redemption'], epoch: 'Second Epoch' },
    { id: 22, name: 'Lord of Storms', gender: 'Male', species: ['Human'], pathway: ['Tyrant'], sequence: 0, volume: 1, affiliation: ['Church of the Lord of Storms', 'Rose Redemption'], epoch: 'Third Epoch' },
    { id: 23, name: 'Primordial Demoness', gender: 'Female', species: ['Human'], pathway: ['Demoness'], sequence: 0, volume: 1, affiliation: ['Demoness Sect'], epoch: 'Fourth Epoch' },
    { id: 24, name: 'Roselle Gustav', gender: 'Male', species: ['Human'], pathway: 'Black Emperor', sequence: 0, volume: 1, affiliation: ['Twilight Hermit Order'], epoch: 'Pre-Epoch' },
    { id: 25, name: 'Salinger', gender: 'Male', species: ['Feathered Serpent'], pathway: ['Death'], sequence: 0, volume: 2, affiliation: ['Rose Redemption'], epoch: 'Second Epoch' },
    { id: 26, name: 'Solomon', gender: 'Male', species: ['Human'], pathway: ['Black Emperor'], sequence: 0, volume: 1, affiliation: ['❌'], epoch: 'Fourth Epoch' },
    { id: 27, name: 'Soniathrym', gender: 'Male', species: ['Elf'], pathway: ['Tyrant'], sequence: 0, volume: 2, affiliation: ['❌'], epoch: 'Second Epoch' },
    { id: 28, name: 'True Creator', gender: 'Male', species: ['Mythical Creature'], pathway: ['Hanged Man'], sequence: 0, volume: 1, affiliation: ['Aurora Order'], epoch: 'Third Epoch' },
    { id: 29, name: 'Trunsoest', gender: 'Male', species: ['Human'], pathway: ['Justiciar'], sequence: 0, volume: 2, affiliation: ['❌'], epoch: 'Fourth Epoch' },

    //Angels
    { id: 30, name: 'Amon', gender: 'Male', species: 'Mythical Creature', pathway: 'Error', sequence: 2, volume: 1, affiliation: ['ASG King of Angels'], epoch: 'Third Epoch' },
    { id: 31, name: 'Antigonus', gender: 'Male', species: ['Demonic Wolf'], pathway: 'Fool', sequence: 2, volume: 1, affiliation: ['❌'], epoch: 'Second Epoch' },
    { id: 32, name: 'Azik Eggers', gender: 'Male', species: ['Feathered Serpent'], pathway: 'Death', sequence: 2, volume: 1, affiliation: ['Church of the Fool'], epoch: 'Fourth Epoch' },
    { id: 33, name: 'Kotar', gender: 'Male', species: ['Demonic Wolf'], pathway: 'Fool', sequence: 2, volume: 6, affiliation: ['❌'], epoch: 'Second Epoch' },
    { id: 34, name: 'Zaratul', gender: 'Male', species: ['Human'], pathway: 'Fool', sequence: 2, volume: 1, affiliation: ['Secret Order'], epoch: 'Fourth Epoch' },
    { id: 35, name: 'Alzuhod', gender: 'Male', species: ['Dragon'], pathway: ['Visionary'], sequence: 1, volume: 2, affiliation: ['❌'], epoch: 'Second Epoch' },
    { id: 36, name: 'Auernia', gender: 'Female', species: ['Sanguine'], pathway: ['Moon'], sequence: 1, volume: 2, affiliation: ['Sanguines'], epoch: 'Second Epoch' },
    { id: 37, name: 'Cohinem', gender: 'Female', species: ['Elf'], pathway: ['Tyrant'], sequence: 2, volume: 3, affiliation: ['❌'], epoch: 'Pre-Epoch' },
    { id: 38, name: 'Einhorn', gender: 'Male', species: ['Human'], pathway: ['Red Priest'], sequence: 1, volume: 4, affiliation: ['❌'], epoch: 'Fourth Epoch' },
    { id: 39, name: 'George Augustus III', gender: 'Male', species: ['Human'], pathway: ['Black Emperor'], sequence: 1, volume: 1, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 40, name: 'Larrion', gender: 'Male', species: ['Human'], pathway: ['Twilight Giant'], sequence: 2, volume: 7, affiliation: ['Church of the God of Combat'], epoch: 'Fifth Epoch' },
    { id: 41, name: 'Sauron', gender: 'Male', species: ['Human'], pathway: ['Red Priest'], sequence: 1, volume: 4, affiliation: ['❌'], epoch: 'Fourth Epoch' },
    { id: 42, name: 'Suah', gender: 'Male', species: ['Mythical Creature'], pathway: ['Chained'], sequence: 1, volume: 3, affiliation: ['Rose School of Thought'], epoch: 'Fifth Epoch' },
    { id: 43, name: 'Will Auceptin', gender: 'Male', species: ['Mythical Creature'], pathway: ['Wheel of Fortune'], sequence: 1, volume: 2, affiliation: ['Church of the Fool'], epoch: 'Fourth Epoch' },
    { id: 44, name: 'Pallez Zoroast', gender: 'Male', species: ['Human'], pathway: 'Error', sequence: 2, volume: 3, affiliation: ['Church of the Fool', 'Zoroast Family'], epoch: 'Fourth Epoch' },
    { id: 45, name: 'Bethel Abraham', gender: 'Male', species: ['Human'], pathway: ['Door'], sequence: 1, volume: 2, affiliation: ['Abraham Family'], epoch: 'Third Epoch' },
    { id: 46, name: 'Chained God', gender: 'Male', species: ['Mutant'], pathway: ['Chained'], sequence: 1, volume: 1, affiliation: ['Rose Redemption', 'Rose School of Thought'], epoch: 'Second Epoch' },
    { id: 47, name: 'Medici', gender: 'Male', species: ['Mythical Creature'], pathway: ['Red Priest'], sequence: 1, volume: 2, affiliation: ['Rose Redemption'], epoch: 'Second Epoch' },
    { id: 48, name: 'Ouroboros', gender: 'Male', species: ['Mythical Creature'], pathway: ['Wheel of Fortune'], sequence: 1, volume: 2, affiliation: ['Rose Redemption', 'Aurora Order'], epoch: 'Second Epoch' },
    { id: 49, name: 'Sasrir', gender: 'Male', species: ['Mythical Creature'], pathway: ['Hanged Man'], sequence: 1, volume: 3, affiliation: ['Rose Redemption'], epoch: 'Third Epoch' },

    //Saints

    { id: 50, name: 'Alger Wilson', gender: 'Male', species: ['Human','Elf'], pathway: 'Tyrant', sequence: 4, volume: 1, affiliation: ['Tarot Club','Church of the Lord of Storms'], epoch: 'Fifth Epoch' },
    { id: 51, name: 'Audrey Hall', gender: 'Female', species: ['Human'], pathway: 'Visionary', sequence: 3, volume: 1, affiliation: ['Tarot Club','Psychology Alchemists'], epoch: 'Fifth Epoch' },
    { id: 52, name: 'Derrick Berg', gender: 'Male', species: ['Human'], pathway: 'Sun', sequence: 4, volume: 1, affiliation: ['Tarot Club','City Of Silver'], epoch: 'Fifth Epoch' },
    { id: 53, name: 'Fors Wall', gender: 'Female', species: ['Human'], pathway: 'Door', sequence: 4, volume: 1, affiliation: ['Tarot Club','Abraham Family'], epoch: 'Fifth Epoch' },
    { id: 54, name: 'Emlyn White', gender: 'Male', species: ['Sanguine'], pathway: 'Moon', sequence: 4, volume: 2, affiliation: ['Tarot Club','Sanguines'], epoch: 'Fifth Epoch' },
    { id: 55, name: 'Cattleya', gender: 'Female', species: ['Human'], pathway: 'Hermit', sequence: 3, volume: 3, affiliation: ['Tarot Club','Moses Ascetic Order'], epoch: 'Fifth Epoch' },
    { id: 56, name: 'Leonard Mitchell', gender: 'Male', species: ['Human'], pathway: 'Darkness', sequence: 4, volume: 1, affiliation: ['Tarot Club','Church of the Evernight Goddess'], epoch: 'Fifth Epoch' },
    { id: 57, name: 'Xio Derecha', gender: 'Female', species: ['Human'], pathway: 'Justiciar', sequence: 4, volume: 1, affiliation: ['Tarot Club','MI9'], epoch: 'Fifth Epoch' },
    { id: 58, name: 'Anderson Hood', gender: 'Male', species: ['Human'], pathway: ['Red Priest'], sequence: 4, volume: 3, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 59, name: 'Anthony Stevenson', gender: 'Male', species: ['Human'], pathway: ['Darkness'], sequence: 3, volume: 2, affiliation: ['Church of the Evernight Goddess'], epoch: 'Fifth Epoch' },
    { id: 60, name: 'Botis', gender: 'Male', species: ['Human'], pathway: ['Door'], sequence: 4, volume: 2, affiliation: ['Aurora Order'], epoch: 'Fifth Epoch' },
    { id: 61, name: 'Colin Iliad', gender: 'Male', species: ['Human'], pathway: ['Twilight Giant'], sequence: 3, volume: 1, affiliation: ['City of Silver'], epoch: 'Fifth Epoch' },
    { id: 62, name: 'Crestet Cesimir', gender: 'Male', species: ['Human'], pathway: ['Darkness'], sequence: 4, volume: 1, affiliation: ['Church of the Evernight Goddess'], epoch: 'Fifth Epoch' },
    { id: 63, name: 'Flora Jacob', gender: 'Female', species: ['Human'], pathway: 'Error', sequence: 4, volume: 4, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 64, name: 'Hawick', gender: 'Male', species: ['Human'], pathway: ['Death'], sequence: 3, volume: 2, affiliation: ['City of Silver'], epoch: 'Fifth Epoch' },
    { id: 65, name: 'Hvin Rambis', gender: 'Male', species: ['Human'], pathway: ['Visionary'], sequence: 4, volume: 4, affiliation: ['Psychology Alchemists'], epoch: 'Fifth Epoch' },
    { id: 66, name: 'Ilya', gender: 'Female', species: ['Human'], pathway: ['Darkness'], sequence: 3, volume: 4, affiliation: ['Church of the Evernight Goddess'], epoch: 'FIfth Epoch' },
    { id: 67, name: 'Ince Zangwill', gender: 'Male', species: ['Human'], pathway: 'Darkness', sequence: 4, volume: 1, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 68, name: 'Jahn Kottman', gender: 'Male', species: ['Human'], pathway: ['Tyrant'], sequence: 3, volume: 3, affiliation: ['Church of the Lord of Storms'], epoch: 'Fifth Epoch' },
    { id: 69, name: 'Kalvetua', gender: 'Male', species: ['Sea Serpent Spirit'], pathway: ['Tyrant'], sequence: 3, volume: 3, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 70, name: 'Katarina Pelle', gender: 'Female', species: ['Human'], pathway: ['Demoness'], sequence: 3, volume: 1, affiliation: ['Demoness Sect'], epoch: 'Fifth Epoch' },
    { id: 71, name: 'Kisma', gender: 'Male', species: ['Human'], pathway: ['Hanged Man'], sequence: 4, volume: 2, affiliation: ['Aurora Order'], epoch: 'Fifth Epoch' },
    { id: 72, name: 'Klarman', gender: 'Male', species: ['Human'], pathway: ['Moon'], sequence: 4, volume: 2, affiliation: ['Rose School of Thought'], epoch: 'Fifth Epoch' },
    { id: 73, name: 'Leomaster', gender: 'Male', species: ['Human'], pathway: ['Hanged Man'], sequence: 4, volume: 3, affiliation: ['Aurora Order'], epoch: 'Fifth Epoch' },
    { id: 74, name: 'Lovia Tiffany', gender: 'Female', species: ['Human'], pathway: ['Hanged Man'], sequence: 4, volume: 1, affiliation: ['City of Silver'], epoch: 'Fifth Epoch' },
    { id: 75, name: 'Nast Solomon', gender: 'Male', species: ['Human'], pathway: ['Black Emperor'], sequence: 3, volume: 1, affiliation: ['Pirate King'], epoch: 'FIfth Epoch' },
    { id: 76, name: 'Panatiya', gender: 'Female', species: ['Human'], pathway: ['Demoness'], sequence: 4, volume: 2, affiliation: ['Demoness Sect'], epoch: 'Fifth Epoch' },
    { id: 77, name: 'Patrick Bryan', gender: 'Male', species: ['Human'], pathway: ['Death'], sequence: 4, volume: 4, affiliation: ['Numinous Episcopate'], epoch: 'Fifth Epoch' },
    { id: 78, name: 'Pauli Derlau', gender: 'Male', species: ['Human'], pathway: ['Visionary'], sequence: 3, volume: 5, affiliation: ['Psychology Alchemists'], epoch: 'Fifth Epoch' },
    { id: 79, name: 'Qonas Kilgor', gender: 'Male', species: ['Human'], pathway: ['Black Emperor'], sequence: 4, volume: 3, affiliation: ['MI9'], epoch: 'Fifth Epoch' },
    { id: 80, name: 'Sharron (Miss Bodyguard)', gender: 'Female', species: ['Human'], pathway: ['Chained'], sequence: 4, volume: 2, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 81, name: 'Trissy', gender: 'Female', species: ['Human'], pathway: ['Demoness'], sequence: 4, volume: 1, affiliation: ['❌'], epoch: 'Fifth Epoch' },

    //Mid Sequences

    { id: 82, name: 'Alfred Hall', gender: 'Male', species: ['Human'], pathway: ['Justiciar'], sequence: 5, volume: 1, affiliation: ['MI9'], epoch: 'Fifth Epoch' },
    { id: 83, name: 'Bakerland Jean Madan', gender: 'Male', species: ['Human'], pathway: ['Red Priest'], sequence: 6, volume: 2, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 84, name: 'Cosmi Odora', gender: 'Male', species: ['Sanguine'], pathway: ['Moon'], sequence: 6, volume: 2, affiliation: ['Sanguines', 'Church of the Earth Mother'], epoch: 'Fifth Epoch' },
    { id: 85, name: 'Daly Simone', gender: 'Female', species: 'Human', pathway: 'Death', sequence: 5, volume: 1, affiliation: ['Church of the Evernight Goddess'], epoch: 'Fifth Epoch' },
    { id: 86, name: 'Danitz Dubois', gender: 'Male', species: ['Human'], pathway: ['Red Priest'], sequence: 6, volume: 3, affiliation: ['Church of the Fool', 'Golden Dream Pirates'], epoch: 'Fifth Epoch' },
    { id: 87, name: 'Devil Dog', gender: 'Male', species: ['Dog'], pathway: ['Abyss'], sequence: 6, volume: 2, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 88, name: 'Dorian Gray Abraham', gender: 'Male', species: ['Human'], pathway: ['Door'], sequence: 7, volume: 2, affiliation: ['Abraham Family'], epoch: 'Fifth Epoch' },
    { id: 89, name: 'Dunn Smith', gender: 'Male', species: 'Human', pathway: 'Darkness', sequence: 7, volume: 1, affiliation: ['Church of the Evernight Goddess'], epoch: 'Fifth Epoch' },
    { id: 90, name: 'Edwina Edwards', gender: 'Female', species: ['Human'], pathway: ['White Tower'], sequence: 5, volume: 3, affiliation: ['Church of the God of Knowledge and Wisdom', 'Golden Dream Pirates'], epoch: 'Fifth Epoch' },
    { id: 91, name: 'Ernes Boyar', gender: 'Male', species: ['Sanguine'], pathway: ['Moon'], sequence: 5, volume: 5, affiliation: ['Sanguines', 'Church of the Earth Mother'], epoch: 'Fifth Epoch' },
    { id: 92, name: 'Frank Lee', gender: 'Male', species: ['Human'], pathway: ['Mother'], sequence: 5, volume: 3, affiliation: ['The Future'], epoch: 'Fifth Epoch' },
    { id: 93, name: 'Frye', gender: 'Male', species: ['Human'], pathway: ['Death'], sequence: 7, volume: 1, affiliation: ['Church of the Evernight Goddess'], epoch: 'Fifth Epoch' },
    { id: 94, name: 'Galis Kevin', gender: 'Male', species: ['Human'], pathway: ['Moon'], sequence: 7, volume: 4, affiliation: ['Rose School of Thought'], epoch: 'Fifth Epoch' },
    { id: 95, name: 'Groselle', gender: 'Male', species: ['Giant'], pathway: ['Twilight Giant'], sequence: 5, volume: 3, affiliation: ['❌'], epoch: 'Second Epoch' },
    { id: 96, name: 'Hazel Macht', gender: 'Female', species: ['Human'], pathway: 'Error', sequence: 7, volume: 4, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 97, name: 'Helene', gender: 'Female', species: ['Human'], pathway: ['Red Priest'], sequence: 7, volume: 3, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 98, name: 'Hood Eugen', gender: 'Male', species: ['Human'], pathway: ['Visionary'], sequence: 7, volume: 1, affiliation: ['Psychology Alchemists'], epoch: 'Fifth Epoch' },
    { id: 99, name: 'Isengard Stanton', gender: 'Male', species: ['Human'], pathway: ['White Tower'], sequence: 7, volume: 1, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 100, name: 'Jason', gender: 'Male', species: ['Human'], pathway: ['Chained'], sequence: 6, volume: 2, affiliation: ['Rose School of Thought'], epoch: 'Fifth Epoch' },
    { id: 101, name: 'Jason Beria', gender: 'Male', species: ['Human'], pathway: ['Abyss'], sequence: 5, volume: 2, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 102, name: 'Lawrence Nord', gender: 'Male', species: ['Human'], pathway: ['Door'], sequence: 7, volume: 2, affiliation: ['Abraham Family'], epoch: 'Fifth Epoch' },
    { id: 103, name: 'Mr. X', gender: 'Male', species: ['Human'], pathway: ['Door'], sequence: 5, volume: 3, affiliation: ['Aurora Order'], epoch: 'Fifth Epoch' },
    { id: 104, name: 'Ludwell', gender: 'Male', species: ['Human'], pathway: ['Death'], sequence: 5, volume: 3, affiliation: ['Numinous Episcopate'], epoch: 'Fifth Epoch' },
    { id: 105, name: 'Maric', gender: 'Male', species: ['Human'], pathway: ['Chained'], sequence: 5, volume: 2, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 106, name: 'Mason Dere', gender: 'Male', species: ['Human'], pathway: ['Justiciar'], sequence: 5, volume: 5, affiliation: ['MI9'], epoch: 'Fifth Epoch' },
    { id: 107, name: 'Mobet Zoroast', gender: 'Male', species: ['Human'], pathway: ['Error'], sequence: 5, volume: 3, affiliation: ['Zoroast Family'], epoch: 'Fourth Epoch' },
    { id: 108, name: 'Mr. A', gender: 'Male', species: ['Human'], pathway: ['Hanged Man'], sequence: 5, volume: 2, affiliation: ['Aurora Order'], epoch: 'Fifth Epoch' },
    { id: 109, name: 'Mr. Z', gender: 'Male', species: ['Human'], pathway: ['Hanged Man'], sequence: 5, volume: 1, affiliation: ['Aurora Order'], epoch: 'Fifth Epoch' },
    { id: 110, name: 'Qilangos', gender: 'Male', species: ['Human'], pathway: ['Tyrant'], sequence: 6, volume: 1, affiliation: ['Twilight Hermit Order'], epoch: 'Fifth Epoch' },
    { id: 111, name: 'Rosago', gender: 'Male', species: ['Human'], pathway: ['Fool'], sequence: 5, volume: 2, affiliation: ['Secret Order'], epoch: 'Fifth Epoch' },
    { id: 112, name: 'Senor', gender: 'Male', species: ['Human'], pathway: ['Chained'], sequence: 5, volume: 3, affiliation: ['Rose School of Thought'], epoch: 'Fifth Epoch' },
    { id: 113, name: 'Sharon', gender: 'Female', species: ['Human'], pathway: ['Demoness'], sequence: 6, volume: 1, affiliation: ['Demoness Sect'], epoch: 'Fifth Epoch' },
    { id: 114, name: 'Shermane', gender: 'Female', species: ['Human'], pathway: ['Demoness'], sequence: 7, volume: 4, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 115, name: 'Siatas', gender: 'Female', species: ['Elf'], pathway: ['Tyrant'], sequence: 5, volume: 3, affiliation: ['❌'], epoch: 'Second Epoch' },
    { id: 116, name: 'Snowman', gender: 'Male', species: ['Human'], pathway: ['Sun'], sequence: 5, volume: 3, affiliation: ['❌'], epoch: 'Third Epoch' },
    { id: 117, name: 'Soest', gender: 'Male', species: ['Human'], pathway: ['Darkness'], sequence: 5, volume: 2, affiliation: ['Church of the Evernight Goddess'], epoch: 'Fifth Epoch' },
    { id: 118, name: 'Steve', gender: 'Male', species: ['Human'], pathway: ['Chained'], sequence: 5, volume: 2, affiliation: ['Rose School of Thought'], epoch: 'Fifth Epoch' },
    { id: 119, name: 'Suited Clown', gender: 'Male', species: ['Human'], pathway: ['Fool'], sequence: 7, volume: 1, affiliation: ['Secret Order'], epoch: 'Fifth Epoch' },
    { id: 120, name: 'Susie', gender: 'Female', species: ['Dog'], pathway: ['Visionary'], sequence: 5, volume: 1, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 121, name: 'Tracy', gender: 'Female', species: ['Human'], pathway: ['Demoness'], sequence: 5, volume: 2, affiliation: ['Demoness Sect'], epoch: 'Fifth Epoch' },
    { id: 122, name: 'Tyre', gender: 'Male', species: ['Human'], pathway: ['Chained'], sequence: 7, volume: 2, affiliation: ['Rose School of Thought'], epoch: 'Fifth Epoch' },
    { id: 123, name: 'Utravsky', gender: 'Male', species: ['Human'], pathway: ['Twilight Giant'], sequence: 6, volume: 2, affiliation: ['Church of the Earth Mother'], epoch: 'Fifth Epoch' },
    { id: 124, name: 'Verdu Garcia', gender: 'Male', species: ['Human'], pathway: ['Door'], sequence: 7, volume: 7, affiliation: ['Abraham Family'], epoch: 'Fifth Epoch' },

    // Low Sequences
    { id: 125, name: 'Biles', gender: 'Male', species: ['Human'], pathway: ['Tyrant'], sequence: 9, volume: 7, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 126, name: 'Glaint', gender: 'Male', species: ['Human'], pathway: ['Moon'], sequence: 9, volume: 1, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 127, name: 'Hanass Vincent', gender: 'Male', species: ['Human'], pathway: ['Hanged Man'], sequence: 9, volume: 1, affiliation: ['Aurora Order'], epoch: 'Fifth Epoch' },
    { id: 128, name: 'Kenley White', gender: 'Male', species: ['Human'], pathway: ['Darkness'], sequence: 9, volume: 1, affiliation: ['Church of the Evernight Goddess'], epoch: 'Fifth Epoch' },
    { id: 129, name: 'Lanevus', gender: 'Male', species: ['Human'], pathway: ['Error'], sequence: 8, volume: 1, affiliation: ['Aurora Order'], epoch: 'Fifth Epoch' },
    { id: 130, name: 'Melissa Moretti', gender: 'Female', species: ['Human'], pathway: ['Paragon'], sequence: 9, volume: 1, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 131, name: 'Old Neil', gender: 'Male', species: ['Human'], pathway: ['Hermit'], sequence: 9, volume: 1, affiliation: ['Church of the Evernight Goddess'], epoch: 'Fifth Epoch' },
    { id: 132, name: 'Pasha', gender: 'Female', species: ['Human'], pathway: ['Red Priest'], sequence: 9, volume: 7, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 133, name: 'Phil', gender: 'Male', species: ['Human'], pathway: ['Error'], sequence: 9, volume: 7, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 134, name: 'Roy', gender: 'Male', species: ['Human'], pathway: ['Twilight Giant'], sequence: 9, volume: 7, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 135, name: 'Rafter Pound', gender: 'Male', species: ['Human'], pathway: ['Black Emperor'], sequence: 9, volume: 2, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 136, name: 'Sirius Arapis', gender: 'Male', species: ['Human'], pathway: ['Hanged Man'], sequence: 9, volume: 1, affiliation: ['Aurora Order'], epoch: 'Fifth Epoch' },



    // Not Beyonders
    { id: 137, name: 'Aaron Ceres', gender: 'Male', species: ['Human'], pathway: ['❌'], sequence: '❌', volume: 2, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 138, name: 'Alice Moretti', gender: 'Female', species: ['Human'], pathway: ['❌'], sequence: '❌', volume: 8, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 139, name: 'Benson Moretti', gender: 'Male', species: ['Human'], pathway: ['❌'], sequence: '❌', volume: 1, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 140, name: 'Caitlyn Hall', gender: 'Female', species: ['Human'], pathway: ['❌'], sequence: '❌', volume: 2, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 141, name: 'Capim', gender: 'Male', species: ['Human'], pathway: ['❌'], sequence: '❌', volume: 2, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 142, name: 'Daisy', gender: 'Female', species: ['Human'], pathway: ['❌'], sequence: '❌', volume: 2, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 143, name: 'Earl Hall', gender: 'Male', species: ['Human'], pathway: ['❌'], sequence: '❌', volume: 1, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 144, name: 'Edessak Augustus', gender: 'Male', species: ['Human'], pathway: ['❌'], sequence: '❌', volume: 2, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 145, name: 'Elizabeth', gender: 'Female', species: ['Human'], pathway: ['❌'], sequence: '❌', volume: 1, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 146, name: 'Hibbert Hall', gender: 'Male', species: ['Human'], pathway: ['❌'], sequence: '❌', volume: 2, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 147, name: 'Ian Wright', gender: 'Male', species: ['Human'], pathway: ['❌'], sequence: '❌', volume: 2, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 148, name: 'Megose', gender: 'Female', species: ['Human'], pathway: ['❌'], sequence: '❌', volume: 1, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 149, name: 'Old Kohler', gender: 'Male', species: ['Human'], pathway: ['❌'], sequence: '❌', volume: 2, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 150, name: 'Ray Bieber', gender: 'Male', species: ['Human'], pathway: ['❌'], sequence: '❌', volume: 1, affiliation: ['❌'], epoch: 'Fifth Epoch' },
    { id: 151, name: 'Rozanne', gender: 'Female', species: ['Human'], pathway: ['❌'], sequence: '❌', volume: 1, affiliation: ['Church of the Evernight Goddess'], epoch: 'Fifth Epoch' },

    // New Add
    { id: 152, name: 'Reinette Tinekerr', gender: 'Female', species: ['Human'], pathway: ['Chained'], sequence: 2, volume: 3, affiliation: ['Church of the Fool'], epoch: 'Fifth Epoch' },
    { id: 153, name: 'Bernadette Gustav', gender: 'Female', species: ['Human'], pathway: ['Hermit'], sequence: 2, volume: 2, affiliation: ['Pirate King'], epoch: 'Fifth Epoch' },
]